#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

usage() {
    cat <<EOF
Usage: $(basename "$0") [options] [<base-tag> [<branch-name>]]

Apply JetBrains CMake patches to a release tag.

With no arguments, lists available tags and prompts interactively.
With one argument, derives branch name: v4.3.0 → v4.3.0-clion.

Options:
  -f        Delete and recreate branch if it already exists
  --push    Push branch to origin after applying patches

Examples:
  ./apply.sh                              # interactive
  ./apply.sh v4.3.0                       # auto → v4.3.0-clion
  ./apply.sh v4.3.0 v4.3.0-clion         # explicit branch name
  ./apply.sh -f v4.3.0 --push            # force recreate + push
EOF
    exit 1
}

# Generate resume.sh in worktree for manual conflict resolution
generate_resume() {
    local worktree_dir="$1" failed_patch="$2"
    local all_patches_str="$3" remaining_str="$4"

    cat > "$worktree_dir/resume.sh" <<'RESUME_HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by apply.sh — resumes after a failed patch.
# Fix the rejects, delete .rej files, then run this script.

RESUME_HEADER

    cat >> "$worktree_dir/resume.sh" <<RESUME_VARS
FAILED_PATCH="$failed_patch"
ALL_PATCHES=($all_patches_str)
REMAINING=($remaining_str)
RESUME_VARS

    cat >> "$worktree_dir/resume.sh" <<'RESUME_BODY'

# Step 1: Check rejects are resolved
rejects=$(find . -name '*.rej' 2>/dev/null || true)
if [[ -n "$rejects" ]]; then
    echo "Unresolved rejects — fix these first:"
    echo "$rejects"
    exit 1
fi

# Step 2: Commit the fixed patch
echo "Committing resolved patch: $FAILED_PATCH"
git add -A
git commit -m "Apply $FAILED_PATCH"

# Step 3: Apply remaining patches
for patch_file in "${REMAINING[@]}"; do
    patch_name="$(basename "$patch_file")"
    echo "Applying $patch_name..."
    if ! git am --3way "$patch_file"; then
        git am --abort 2>/dev/null || true
        if ! patch -p1 < "$patch_file"; then
            echo
            echo "FAILED to apply $patch_name"
            echo "Fix rejects, delete .rej files, then:"
            echo "  git add -A && git commit -m 'Apply $patch_name'"
            echo "  # apply remaining patches manually"
            exit 1
        fi
        git add -A
        git commit -m "Apply $patch_name"
    fi
done

# Step 4: Clean up
rm -f resume.sh
git add -A
git diff --cached --quiet || git commit -m "Remove resume.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo
echo "All patches applied to $BRANCH."
echo "  git push origin $BRANCH"
echo "  cd .. && git worktree remove $(pwd)"
RESUME_BODY

    chmod +x "$worktree_dir/resume.sh"
}

# Generate claudefix.sh that launches Claude Code to resolve rejects
generate_claudefix() {
    local worktree_dir="$1" branch_name="$2"

    cat > "$SCRIPT_DIR/claudefix.sh" <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail
HEADER

    cat >> "$SCRIPT_DIR/claudefix.sh" <<VARS
WORKTREE_DIR="$worktree_dir"
BRANCH_NAME="$branch_name"
SCRIPT_DIR="$SCRIPT_DIR"
VARS

    cat >> "$SCRIPT_DIR/claudefix.sh" <<'BODY'

rejects=$(find "$WORKTREE_DIR" -name '*.rej' 2>/dev/null || true)
if [[ -z "$rejects" ]]; then
    echo "No .rej files found in $WORKTREE_DIR"
    exit 0
fi

reject_list=""
while IFS= read -r rej; do
    reject_list+="  $rej
"
done <<< "$rejects"

prompt="You are fixing failed CMake patch applications.

## Worktree: $WORKTREE_DIR (branch: $BRANCH_NAME)

Reject files:
$reject_list
Instructions:
1. Read each .rej file to understand the intended change
2. Read the corresponding source file (same path without .rej)
3. Apply the intended change to the source file using the Edit tool
4. Delete the .rej file
5. After all rejects are resolved, run: cd $WORKTREE_DIR && ./resume.sh

IMPORTANT: Do NOT run git push or push any branches yourself."

exec claude "$prompt"
BODY

    chmod +x "$SCRIPT_DIR/claudefix.sh"
}

# --- Main ---

# Parse arguments
FORCE=false
PUSH=false
POSITIONAL=()
for arg in "$@"; do
    case "$arg" in
        -f)        FORCE=true ;;
        --push)    PUSH=true ;;
        -h|--help) usage ;;
        -*)        echo "Unknown option: $arg" >&2; usage ;;
        *)         POSITIONAL+=("$arg") ;;
    esac
done

# Interactive mode when no positional args given
if [[ ${#POSITIONAL[@]} -eq 0 ]]; then
    mapfile -t tags < <(git -C "$REPO_ROOT" tag -l 'v[0-9]*' --sort=-v:refname \
        | grep -v -- '-rc')
    if [[ ${#tags[@]} -eq 0 ]]; then
        echo "No release tags found. Run bootstrap.sh first." >&2
        exit 1
    fi

    echo "Available CMake release tags (most recent first):"
    echo
    # Show first 20
    for i in "${!tags[@]}"; do
        (( i >= 20 )) && break
        printf "  %2d) %s\n" $((i + 1)) "${tags[$i]}"
    done
    if (( ${#tags[@]} > 20 )); then
        echo "  ... (${#tags[@]} total, showing first 20)"
    fi
    echo
    read -rp "Select tag [1-${#tags[@]}]: " choice

    if ! [[ "$choice" =~ ^[0-9]+$ ]] || (( choice < 1 || choice > ${#tags[@]} )); then
        echo "Invalid selection." >&2
        exit 1
    fi

    BASE_TAG="${tags[$((choice - 1))]}"
    BRANCH_NAME="${BASE_TAG}-clion"

    echo
    flags=""
    $FORCE && flags+=" -f"
    $PUSH && flags+=" --push"
    echo "Will run: apply.sh${flags} $BASE_TAG $BRANCH_NAME"
    read -rp "Proceed? [Y/n] " confirm
    [[ "${confirm:-y}" =~ ^[Yy]?$ ]] || exit 0

elif [[ ${#POSITIONAL[@]} -eq 1 ]]; then
    BASE_TAG="${POSITIONAL[0]}"
    BRANCH_NAME="${BASE_TAG}-clion"
elif [[ ${#POSITIONAL[@]} -eq 2 ]]; then
    BASE_TAG="${POSITIONAL[0]}"
    BRANCH_NAME="${POSITIONAL[1]}"
else
    usage
fi

# Verify base tag exists
if ! git -C "$REPO_ROOT" rev-parse --verify "$BASE_TAG" >/dev/null 2>&1; then
    echo "Error: tag '$BASE_TAG' does not exist." >&2
    exit 1
fi

# Extract CMake version from tag (e.g. v4.3.0 → 4.3.0)
if [[ "$BASE_TAG" =~ ^v([0-9]+(\.[0-9]+)*) ]]; then
    CMAKE_VERSION="${BASH_REMATCH[1]}"
else
    echo "Error: cannot extract version from '$BASE_TAG' (expected v<major>.<minor>.<patch>)" >&2
    exit 1
fi

# Resolve versioned manifest file.
# Lookup order: manifests/<major>.<minor>.<patch>.manifest,
#               manifests/<major>.<minor>.manifest,
#               manifests/<major>.manifest
MANIFEST_FILE=""
IFS='.' read -ra parts <<< "$CMAKE_VERSION"
for (( depth=${#parts[@]}; depth >= 1; depth-- )); do
    candidate_ver=""
    for (( i=0; i < depth; i++ )); do
        [[ -n "$candidate_ver" ]] && candidate_ver+="."
        candidate_ver+="${parts[$i]}"
    done
    candidate="$SCRIPT_DIR/manifests/${candidate_ver}.manifest"
    if [[ -f "$candidate" ]]; then
        MANIFEST_FILE="$candidate"
        break
    fi
done

if [[ -z "$MANIFEST_FILE" ]]; then
    echo "Error: no manifest found for CMake $CMAKE_VERSION" >&2
    echo "  looked for:" >&2
    for (( depth=${#parts[@]}; depth >= 1; depth-- )); do
        candidate_ver=""
        for (( i=0; i < depth; i++ )); do
            [[ -n "$candidate_ver" ]] && candidate_ver+="."
            candidate_ver+="${parts[$i]}"
        done
        echo "    manifests/${candidate_ver}.manifest" >&2
    done
    exit 1
fi

# Read patch list from manifest (flat list, no [platform] sections)
PATCHES=()
while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    local_path="$SCRIPT_DIR/$line"
    if [[ ! -f "$local_path" ]]; then
        echo "Error: patch '$line' listed in manifest not found at $local_path" >&2
        exit 1
    fi
    PATCHES+=("$local_path")
done < "$MANIFEST_FILE"

echo "Tag:      $BASE_TAG ($(git -C "$REPO_ROOT" rev-parse --short "$BASE_TAG"))"
echo "Branch:   $BRANCH_NAME"
echo "Manifest: $MANIFEST_FILE (${#PATCHES[@]} patches)"
echo

# Create branch from base tag
if git -C "$REPO_ROOT" rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
    if $FORCE; then
        # Remove any worktree attached to this branch first
        old_wt=$(git -C "$REPO_ROOT" worktree list --porcelain \
            | grep -B2 "branch refs/heads/$BRANCH_NAME" \
            | grep '^worktree ' | sed 's/^worktree //' || true)
        if [[ -n "$old_wt" ]]; then
            git -C "$REPO_ROOT" worktree remove --force "$old_wt" 2>/dev/null || true
        fi
        git -C "$REPO_ROOT" branch -D "$BRANCH_NAME" >/dev/null
    else
        echo "Error: branch '$BRANCH_NAME' already exists (use -f to recreate)." >&2
        exit 1
    fi
fi
git -C "$REPO_ROOT" branch "$BRANCH_NAME" "$BASE_TAG"

# Create temporary worktree
worktree_dir=$(mktemp -d "${TMPDIR:-/tmp}/cmake-patches-XXXXXX")
git -C "$REPO_ROOT" worktree add "$worktree_dir" "$BRANCH_NAME" >/dev/null 2>&1

# Apply patches one by one
pushd "$worktree_dir" >/dev/null
for (( i = 0; i < ${#PATCHES[@]}; i++ )); do
    patch_file="${PATCHES[$i]}"
    patch_name="$(basename "$patch_file")"

    if patch_output=$(git am --3way "$patch_file" 2>&1); then
        echo "  ✅ $patch_name"
    else
        echo "  ❌ $patch_name"
        echo "$patch_output" | sed 's/^/     /'
        git am --abort 2>/dev/null || true

        # Fall back to patch(1) so we get .rej files for manual fixing
        if patch_output2=$(patch -p1 < "$patch_file" 2>&1); then
            echo "     (applied with patch -p1, committing)"
            git add -A
            git commit -q -m "Apply $patch_name"
            echo "  ✅ $patch_name (via patch)"
            continue
        fi
        echo "$patch_output2" | sed 's/^/     /'

        # Collect remaining patches
        remaining=()
        for (( j = i + 1; j < ${#PATCHES[@]}; j++ )); do
            remaining+=("${PATCHES[$j]}")
            echo "  ⬜ $(basename "${PATCHES[$j]}")"
        done

        generate_resume "$worktree_dir" "$patch_name" \
            "${PATCHES[*]}" "${remaining[*]}"

        echo
        echo "  To resolve:"
        echo "    cd $worktree_dir"
        echo "    # fix rejects, delete .rej files, then run:"
        echo "    ./resume.sh"
        popd >/dev/null
        generate_claudefix "$worktree_dir" "$BRANCH_NAME"
        exit 1
    fi
done
popd >/dev/null

# Done — clean up worktree
commit_count=$(git -C "$worktree_dir" rev-list --count "$BASE_TAG"..HEAD)
git -C "$REPO_ROOT" worktree remove "$worktree_dir" 2>/dev/null

echo
echo "🟢 $BRANCH_NAME done ($commit_count commits)"

if $PUSH; then
    git -C "$REPO_ROOT" push origin "$BRANCH_NAME"
    echo "Pushed to origin/$BRANCH_NAME"
else
    push_script="$SCRIPT_DIR/push_${BRANCH_NAME}.sh"
    cat > "$push_script" <<PUSH_EOF
#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="$REPO_ROOT"
BRANCH_NAME="$BRANCH_NAME"

echo "Pushing \$BRANCH_NAME..."
git -C "\$REPO_ROOT" push origin "\$BRANCH_NAME"
echo "Done."
rm -f "\$0"
PUSH_EOF
    chmod +x "$push_script"
    echo "To push: $push_script"
fi
